# Generated by Django 5.1.4 on 2025-01-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('service', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=20)),
            ],
        ),
    ]
